// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CollectStarResourcesReducer from "../collect_star_resources_reducer";
import ExecuteBattleReducer from "../execute_battle_reducer";
import InitiateScanReducer from "../initiate_scan_reducer";
import OrderWarpReducer from "../order_warp_reducer";
import PlaceBuildingReducer from "../place_building_reducer";
import RegisterEmpireReducer from "../register_empire_reducer";
import SellShipCargoReducer from "../sell_ship_cargo_reducer";
import SellStarWarehouseReducer from "../sell_star_warehouse_reducer";
import SetShipAttackModeReducer from "../set_ship_attack_mode_reducer";
import SpawnStarterShipReducer from "../spawn_starter_ship_reducer";
import UpgradeBuildingReducer from "../upgrade_building_reducer";

export type CollectStarResourcesParams = __Infer<typeof CollectStarResourcesReducer>;
export type ExecuteBattleParams = __Infer<typeof ExecuteBattleReducer>;
export type InitiateScanParams = __Infer<typeof InitiateScanReducer>;
export type OrderWarpParams = __Infer<typeof OrderWarpReducer>;
export type PlaceBuildingParams = __Infer<typeof PlaceBuildingReducer>;
export type RegisterEmpireParams = __Infer<typeof RegisterEmpireReducer>;
export type SellShipCargoParams = __Infer<typeof SellShipCargoReducer>;
export type SellStarWarehouseParams = __Infer<typeof SellStarWarehouseReducer>;
export type SetShipAttackModeParams = __Infer<typeof SetShipAttackModeReducer>;
export type SpawnStarterShipParams = __Infer<typeof SpawnStarterShipReducer>;
export type UpgradeBuildingParams = __Infer<typeof UpgradeBuildingReducer>;

