// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::building_kind_type::BuildingKind;
use super::material_type::Material;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Building {
    pub id: u64,
    pub star_x: i32,
    pub star_y: i32,
    pub planet_index: u8,
    pub slot_index: u8,
    pub kind: BuildingKind,
    pub level: u32,
    pub degradation_percent: f32,
    pub mining_material: Option<Material>,
    pub warehouse_inventory: Vec<Material>,
}

impl __sdk::InModule for Building {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Building`.
///
/// Provides typed access to columns for query building.
pub struct BuildingCols {
    pub id: __sdk::__query_builder::Col<Building, u64>,
    pub star_x: __sdk::__query_builder::Col<Building, i32>,
    pub star_y: __sdk::__query_builder::Col<Building, i32>,
    pub planet_index: __sdk::__query_builder::Col<Building, u8>,
    pub slot_index: __sdk::__query_builder::Col<Building, u8>,
    pub kind: __sdk::__query_builder::Col<Building, BuildingKind>,
    pub level: __sdk::__query_builder::Col<Building, u32>,
    pub degradation_percent: __sdk::__query_builder::Col<Building, f32>,
    pub mining_material: __sdk::__query_builder::Col<Building, Option<Material>>,
    pub warehouse_inventory: __sdk::__query_builder::Col<Building, Vec<Material>>,
}

impl __sdk::__query_builder::HasCols for Building {
    type Cols = BuildingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuildingCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            star_x: __sdk::__query_builder::Col::new(table_name, "star_x"),
            star_y: __sdk::__query_builder::Col::new(table_name, "star_y"),
            planet_index: __sdk::__query_builder::Col::new(table_name, "planet_index"),
            slot_index: __sdk::__query_builder::Col::new(table_name, "slot_index"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            degradation_percent: __sdk::__query_builder::Col::new(
                table_name,
                "degradation_percent",
            ),
            mining_material: __sdk::__query_builder::Col::new(table_name, "mining_material"),
            warehouse_inventory: __sdk::__query_builder::Col::new(
                table_name,
                "warehouse_inventory",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `Building`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuildingIxCols {
    pub id: __sdk::__query_builder::IxCol<Building, u64>,
}

impl __sdk::__query_builder::HasIxCols for Building {
    type IxCols = BuildingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuildingIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Building {}
