// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::empire_type::Empire;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `empire`.
///
/// Obtain a handle from the [`EmpireTableAccess::empire`] method on [`super::RemoteTables`],
/// like `ctx.db.empire()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire().on_insert(...)`.
pub struct EmpireTableHandle<'ctx> {
    imp: __sdk::TableHandle<Empire>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `empire`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EmpireTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EmpireTableHandle`], which mediates access to the table `empire`.
    fn empire(&self) -> EmpireTableHandle<'_>;
}

impl EmpireTableAccess for super::RemoteTables {
    fn empire(&self) -> EmpireTableHandle<'_> {
        EmpireTableHandle {
            imp: self.imp.get_table::<Empire>("empire"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EmpireInsertCallbackId(__sdk::CallbackId);
pub struct EmpireDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EmpireTableHandle<'ctx> {
    type Row = Empire;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Empire> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EmpireInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireInsertCallbackId {
        EmpireInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EmpireInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EmpireDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireDeleteCallbackId {
        EmpireDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EmpireDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EmpireUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EmpireTableHandle<'ctx> {
    type UpdateCallbackId = EmpireUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EmpireUpdateCallbackId {
        EmpireUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EmpireUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `empire`,
/// which allows point queries on the field of the same name
/// via the [`EmpireIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire().identity().find(...)`.
pub struct EmpireIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Empire, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EmpireTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `empire`.
    pub fn identity(&self) -> EmpireIdentityUnique<'ctx> {
        EmpireIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EmpireIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Empire> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `empire`,
/// which allows point queries on the field of the same name
/// via the [`EmpireNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire().name().find(...)`.
pub struct EmpireNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Empire, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EmpireTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `empire`.
    pub fn name(&self) -> EmpireNameUnique<'ctx> {
        EmpireNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EmpireNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Empire> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Empire>("empire");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Empire>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Empire>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Empire`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait empireQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Empire`.
    fn empire(&self) -> __sdk::__query_builder::Table<Empire>;
}

impl empireQueryTableAccess for __sdk::QueryTableAccessor {
    fn empire(&self) -> __sdk::__query_builder::Table<Empire> {
        __sdk::__query_builder::Table::new("empire")
    }
}
