// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Empire {
    pub identity: __sdk::Identity,
    pub name: String,
    pub credits: u64,
}

impl __sdk::InModule for Empire {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Empire`.
///
/// Provides typed access to columns for query building.
pub struct EmpireCols {
    pub identity: __sdk::__query_builder::Col<Empire, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Empire, String>,
    pub credits: __sdk::__query_builder::Col<Empire, u64>,
}

impl __sdk::__query_builder::HasCols for Empire {
    type Cols = EmpireCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmpireCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            credits: __sdk::__query_builder::Col::new(table_name, "credits"),
        }
    }
}

/// Indexed column accessor struct for the table `Empire`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmpireIxCols {
    pub identity: __sdk::__query_builder::IxCol<Empire, __sdk::Identity>,
    pub name: __sdk::__query_builder::IxCol<Empire, String>,
}

impl __sdk::__query_builder::HasIxCols for Empire {
    type IxCols = EmpireIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmpireIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Empire {}
