// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExecuteBattleArgs {
    pub star_x: u32,
    pub star_y: u32,
}

impl From<ExecuteBattleArgs> for super::Reducer {
    fn from(args: ExecuteBattleArgs) -> Self {
        Self::ExecuteBattle {
            star_x: args.star_x,
            star_y: args.star_y,
        }
    }
}

impl __sdk::InModule for ExecuteBattleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `execute_battle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait execute_battle {
    /// Request that the remote module invoke the reducer `execute_battle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`execute_battle:execute_battle_then`] to run a callback after the reducer completes.
    fn execute_battle(&self, star_x: u32, star_y: u32) -> __sdk::Result<()> {
        self.execute_battle_then(star_x, star_y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `execute_battle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn execute_battle_then(
        &self,
        star_x: u32,
        star_y: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl execute_battle for super::RemoteReducers {
    fn execute_battle_then(
        &self,
        star_x: u32,
        star_y: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ExecuteBattleArgs { star_x, star_y }, callback)
    }
}
