// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::building_kind_type::BuildingKind;
use super::ship_attack_mode_type::ShipAttackMode;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceBuildingArgs {
    pub star_x: i32,
    pub star_y: i32,
    pub planet_index: u8,
    pub slot_index: u8,
    pub kind: BuildingKind,
    pub level: u32,
    pub mining_resource_index: Option<u8>,
    pub garrison_attack_mode: Option<ShipAttackMode>,
}

impl From<PlaceBuildingArgs> for super::Reducer {
    fn from(args: PlaceBuildingArgs) -> Self {
        Self::PlaceBuilding {
            star_x: args.star_x,
            star_y: args.star_y,
            planet_index: args.planet_index,
            slot_index: args.slot_index,
            kind: args.kind,
            level: args.level,
            mining_resource_index: args.mining_resource_index,
            garrison_attack_mode: args.garrison_attack_mode,
        }
    }
}

impl __sdk::InModule for PlaceBuildingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_building`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_building {
    /// Request that the remote module invoke the reducer `place_building` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_building:place_building_then`] to run a callback after the reducer completes.
    fn place_building(
        &self,
        star_x: i32,
        star_y: i32,
        planet_index: u8,
        slot_index: u8,
        kind: BuildingKind,
        level: u32,
        mining_resource_index: Option<u8>,
        garrison_attack_mode: Option<ShipAttackMode>,
    ) -> __sdk::Result<()> {
        self.place_building_then(
            star_x,
            star_y,
            planet_index,
            slot_index,
            kind,
            level,
            mining_resource_index,
            garrison_attack_mode,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `place_building` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_building_then(
        &self,
        star_x: i32,
        star_y: i32,
        planet_index: u8,
        slot_index: u8,
        kind: BuildingKind,
        level: u32,
        mining_resource_index: Option<u8>,
        garrison_attack_mode: Option<ShipAttackMode>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_building for super::RemoteReducers {
    fn place_building_then(
        &self,
        star_x: i32,
        star_y: i32,
        planet_index: u8,
        slot_index: u8,
        kind: BuildingKind,
        level: u32,
        mining_resource_index: Option<u8>,
        garrison_attack_mode: Option<ShipAttackMode>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PlaceBuildingArgs {
                star_x,
                star_y,
                planet_index,
                slot_index,
                kind,
                level,
                mining_resource_index,
                garrison_attack_mode,
            },
            callback,
        )
    }
}
