// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipInTransit {
    pub from_star_x: i32,
    pub from_star_y: i32,
    pub to_star_x: i32,
    pub to_star_y: i32,
    pub depart_at: __sdk::Timestamp,
    pub arrive_at: __sdk::Timestamp,
}

impl __sdk::InModule for ShipInTransit {
    type Module = super::RemoteModule;
}
