// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipStats {
    pub size_kt: u32,
    pub speed_lys: f64,
    pub defense: u32,
    pub attack: u32,
    pub battery_ly: u32,
    pub radar_ly: u32,
}

impl __sdk::InModule for ShipStats {
    type Module = super::RemoteModule;
}
