// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ship_at_planet_type::ShipAtPlanet;
use super::ship_in_transit_type::ShipInTransit;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum ShipLocation {
    AtPlanet(ShipAtPlanet),

    InTransit(ShipInTransit),
}

impl __sdk::InModule for ShipLocation {
    type Module = super::RemoteModule;
}
