// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_type::Material;
use super::ship_attack_mode_type::ShipAttackMode;
use super::ship_stats_type::ShipStats;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ship {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub stats: ShipStats,
    pub cargo: Vec<Material>,
    pub attack_mode: ShipAttackMode,
    pub in_transit: bool,
    pub star_x: i32,
    pub star_y: i32,
    pub transit_from_x: i32,
    pub transit_from_y: i32,
    pub transit_to_x: i32,
    pub transit_to_y: i32,
    pub transit_depart_at: __sdk::Timestamp,
    pub transit_arrive_at: __sdk::Timestamp,
    pub jump_ready_at: __sdk::Timestamp,
    pub health: u32,
}

impl __sdk::InModule for Ship {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Ship`.
///
/// Provides typed access to columns for query building.
pub struct ShipCols {
    pub id: __sdk::__query_builder::Col<Ship, u64>,
    pub owner: __sdk::__query_builder::Col<Ship, __sdk::Identity>,
    pub stats: __sdk::__query_builder::Col<Ship, ShipStats>,
    pub cargo: __sdk::__query_builder::Col<Ship, Vec<Material>>,
    pub attack_mode: __sdk::__query_builder::Col<Ship, ShipAttackMode>,
    pub in_transit: __sdk::__query_builder::Col<Ship, bool>,
    pub star_x: __sdk::__query_builder::Col<Ship, i32>,
    pub star_y: __sdk::__query_builder::Col<Ship, i32>,
    pub transit_from_x: __sdk::__query_builder::Col<Ship, i32>,
    pub transit_from_y: __sdk::__query_builder::Col<Ship, i32>,
    pub transit_to_x: __sdk::__query_builder::Col<Ship, i32>,
    pub transit_to_y: __sdk::__query_builder::Col<Ship, i32>,
    pub transit_depart_at: __sdk::__query_builder::Col<Ship, __sdk::Timestamp>,
    pub transit_arrive_at: __sdk::__query_builder::Col<Ship, __sdk::Timestamp>,
    pub jump_ready_at: __sdk::__query_builder::Col<Ship, __sdk::Timestamp>,
    pub health: __sdk::__query_builder::Col<Ship, u32>,
}

impl __sdk::__query_builder::HasCols for Ship {
    type Cols = ShipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            stats: __sdk::__query_builder::Col::new(table_name, "stats"),
            cargo: __sdk::__query_builder::Col::new(table_name, "cargo"),
            attack_mode: __sdk::__query_builder::Col::new(table_name, "attack_mode"),
            in_transit: __sdk::__query_builder::Col::new(table_name, "in_transit"),
            star_x: __sdk::__query_builder::Col::new(table_name, "star_x"),
            star_y: __sdk::__query_builder::Col::new(table_name, "star_y"),
            transit_from_x: __sdk::__query_builder::Col::new(table_name, "transit_from_x"),
            transit_from_y: __sdk::__query_builder::Col::new(table_name, "transit_from_y"),
            transit_to_x: __sdk::__query_builder::Col::new(table_name, "transit_to_x"),
            transit_to_y: __sdk::__query_builder::Col::new(table_name, "transit_to_y"),
            transit_depart_at: __sdk::__query_builder::Col::new(table_name, "transit_depart_at"),
            transit_arrive_at: __sdk::__query_builder::Col::new(table_name, "transit_arrive_at"),
            jump_ready_at: __sdk::__query_builder::Col::new(table_name, "jump_ready_at"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
        }
    }
}

/// Indexed column accessor struct for the table `Ship`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipIxCols {
    pub id: __sdk::__query_builder::IxCol<Ship, u64>,
    pub owner: __sdk::__query_builder::IxCol<Ship, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Ship {
    type IxCols = ShipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ship {}
