// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnStarterShipArgs {}

impl From<SpawnStarterShipArgs> for super::Reducer {
    fn from(args: SpawnStarterShipArgs) -> Self {
        Self::SpawnStarterShip
    }
}

impl __sdk::InModule for SpawnStarterShipArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_starter_ship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_starter_ship {
    /// Request that the remote module invoke the reducer `spawn_starter_ship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_starter_ship:spawn_starter_ship_then`] to run a callback after the reducer completes.
    fn spawn_starter_ship(&self) -> __sdk::Result<()> {
        self.spawn_starter_ship_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_starter_ship` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_starter_ship_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_starter_ship for super::RemoteReducers {
    fn spawn_starter_ship_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SpawnStarterShipArgs {}, callback)
    }
}
