// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Material,
  ShipAttackMode,
  ShipStats,
} from "./types";


export default __t.row({
  id: __t.u64(),
  owner: __t.identity(),
  get stats() {
    return ShipStats;
  },
  get cargo() {
    return __t.array(Material);
  },
  get attackMode() {
    return ShipAttackMode.name("attack_mode");
  },
  inTransit: __t.bool().name("in_transit"),
  starX: __t.i32().name("star_x"),
  starY: __t.i32().name("star_y"),
  transitFromX: __t.i32().name("transit_from_x"),
  transitFromY: __t.i32().name("transit_from_y"),
  transitToX: __t.i32().name("transit_to_x"),
  transitToY: __t.i32().name("transit_to_y"),
  transitDepartAt: __t.timestamp().name("transit_depart_at"),
  transitArriveAt: __t.timestamp().name("transit_arrive_at"),
  jumpReadyAt: __t.timestamp().name("jump_ready_at"),
  health: __t.u32(),
});
