// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  BuildingKind,
  ShipAttackMode,
} from "./types";

export default {
  starX: __t.i32(),
  starY: __t.i32(),
  planetIndex: __t.u8(),
  slotIndex: __t.u8(),
  get kind() {
    return BuildingKind;
  },
  level: __t.u32(),
  miningResourceIndex: __t.option(__t.u8()),
  get garrisonAttackMode() {
    return __t.option(ShipAttackMode);
  },
};
