// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ScanInitiator,
} from "./types";


export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  empireId: __t.identity().name("empire_id"),
  get scanInitiator() {
    return ScanInitiator.name("scan_initiator");
  },
  initiatorId: __t.u64().name("initiator_id"),
  shipId: __t.u64().name("ship_id"),
  toStarX: __t.i32().name("to_star_x"),
  toStarY: __t.i32().name("to_star_y"),
});
