// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Building = __t.object("Building", {
  id: __t.u64(),
  starX: __t.i32(),
  starY: __t.i32(),
  planetIndex: __t.u8(),
  slotIndex: __t.u8(),
  get kind() {
    return BuildingKind;
  },
  level: __t.u32(),
  degradationPercent: __t.f32(),
  get miningMaterial() {
    return __t.option(Material);
  },
  owner: __t.option(__t.identity()),
  get attackMode() {
    return __t.option(ShipAttackMode);
  },
  health: __t.u32(),
});
export type Building = __Infer<typeof Building>;

// The tagged union or sum type for the algebraic type `BuildingKind`.
export const BuildingKind = __t.enum("BuildingKind", {
  MiningDepot: __t.unit(),
  Warehouse: __t.unit(),
  MilitaryGarrison: __t.unit(),
  SalesDepot: __t.unit(),
  ShipDepot: __t.unit(),
  Radar: __t.unit(),
});
export type BuildingKind = __Infer<typeof BuildingKind>;

export const Empire = __t.object("Empire", {
  identity: __t.identity(),
  name: __t.string(),
  credits: __t.u64(),
});
export type Empire = __Infer<typeof Empire>;

// The tagged union or sum type for the algebraic type `Material`.
export const Material = __t.enum("Material", {
  Iron: __t.f64(),
  Helium: __t.f64(),
});
export type Material = __Infer<typeof Material>;

// The tagged union or sum type for the algebraic type `PlanetType`.
export const PlanetType = __t.enum("PlanetType", {
  Solid: __t.unit(),
  Ocean: __t.unit(),
  Gas: __t.unit(),
});
export type PlanetType = __Infer<typeof PlanetType>;

export const PlayerPresence = __t.object("PlayerPresence", {
  id: __t.u64(),
  starX: __t.i32(),
  starY: __t.i32(),
  empireId: __t.identity(),
  planetGeneratorKey: __t.u64(),
});
export type PlayerPresence = __Infer<typeof PlayerPresence>;

// The tagged union or sum type for the algebraic type `ScanInitiator`.
export const ScanInitiator = __t.enum("ScanInitiator", {
  Radar: __t.unit(),
  Ship: __t.unit(),
});
export type ScanInitiator = __Infer<typeof ScanInitiator>;

export const ScanJob = __t.object("ScanJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  empireId: __t.identity(),
  get scanInitiator() {
    return ScanInitiator;
  },
  initiatorId: __t.u64(),
  shipId: __t.u64(),
  toStarX: __t.i32(),
  toStarY: __t.i32(),
});
export type ScanJob = __Infer<typeof ScanJob>;

export const ScanResult = __t.object("ScanResult", {
  id: __t.u64(),
  empireId: __t.identity(),
  starX: __t.i32(),
  starY: __t.i32(),
  planetGeneratorKey: __t.u64(),
  get planets() {
    return __t.array(ScannedPlanet);
  },
  get dockedShips() {
    return __t.array(ScannedDockedShip);
  },
});
export type ScanResult = __Infer<typeof ScanResult>;

export const ScannedBuildling = __t.object("ScannedBuildling", {
  get kind() {
    return BuildingKind;
  },
  level: __t.u32(),
  degradationPercent: __t.f32(),
  get miningMaterial() {
    return __t.option(Material);
  },
  owner: __t.option(__t.identity()),
  health: __t.u32(),
});
export type ScannedBuildling = __Infer<typeof ScannedBuildling>;

export const ScannedDockedShip = __t.object("ScannedDockedShip", {
  owner: __t.identity(),
  get stats() {
    return ShipStats;
  },
  health: __t.u32(),
});
export type ScannedDockedShip = __Infer<typeof ScannedDockedShip>;

export const ScannedPlanet = __t.object("ScannedPlanet", {
  index: __t.u8(),
  name: __t.string(),
  temperatureK: __t.f64(),
  get planetType() {
    return PlanetType;
  },
  size: __t.u8(),
  richness: __t.f64(),
  get resources() {
    return __t.array(Material);
  },
  get buildlings() {
    return __t.array(ScannedBuildling);
  },
});
export type ScannedPlanet = __Infer<typeof ScannedPlanet>;

export const Ship = __t.object("Ship", {
  id: __t.u64(),
  owner: __t.identity(),
  get stats() {
    return ShipStats;
  },
  get cargo() {
    return __t.array(Material);
  },
  get attackMode() {
    return ShipAttackMode;
  },
  inTransit: __t.bool(),
  starX: __t.i32(),
  starY: __t.i32(),
  transitFromX: __t.i32(),
  transitFromY: __t.i32(),
  transitToX: __t.i32(),
  transitToY: __t.i32(),
  transitDepartAt: __t.timestamp(),
  transitArriveAt: __t.timestamp(),
  jumpReadyAt: __t.timestamp(),
  health: __t.u32(),
});
export type Ship = __Infer<typeof Ship>;

// The tagged union or sum type for the algebraic type `ShipAttackMode`.
export const ShipAttackMode = __t.enum("ShipAttackMode", {
  Defend: __t.unit(),
  StrikeFirst: __t.unit(),
});
export type ShipAttackMode = __Infer<typeof ShipAttackMode>;

export const ShipStats = __t.object("ShipStats", {
  sizeKt: __t.u32(),
  speedLys: __t.f64(),
  defense: __t.u32(),
  attack: __t.u32(),
  batteryLy: __t.u32(),
  radarLy: __t.u32(),
});
export type ShipStats = __Infer<typeof ShipStats>;

export const StarSystemStock = __t.object("StarSystemStock", {
  starLocationId: __t.u128(),
  starX: __t.i32(),
  starY: __t.i32(),
  lastSettledAt: __t.timestamp(),
  capacityKt: __t.f64(),
  get settled() {
    return __t.array(Material);
  },
});
export type StarSystemStock = __Infer<typeof StarSystemStock>;

export const WarpJob = __t.object("WarpJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  shipId: __t.u64(),
  toStarX: __t.i32(),
  toStarY: __t.i32(),
});
export type WarpJob = __Infer<typeof WarpJob>;

