// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BuildingKind,
  Material,
  ShipAttackMode,
} from "./types";


export default __t.row({
  id: __t.u64(),
  starX: __t.i32().name("star_x"),
  starY: __t.i32().name("star_y"),
  planetIndex: __t.u8().name("planet_index"),
  slotIndex: __t.u8().name("slot_index"),
  get kind() {
    return BuildingKind;
  },
  level: __t.u32(),
  degradationPercent: __t.f32().name("degradation_percent"),
  get miningMaterial() {
    return __t.option(Material).name("mining_material");
  },
  owner: __t.option(__t.identity()),
  get attackMode() {
    return __t.option(ShipAttackMode).name("attack_mode");
  },
  health: __t.u32(),
});
