// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Material,
} from "./types";


export default __t.row({
  starLocationId: __t.u128().name("star_location_id"),
  starX: __t.i32().name("star_x"),
  starY: __t.i32().name("star_y"),
  lastSettledAt: __t.timestamp().name("last_settled_at"),
  capacityKt: __t.f64().name("capacity_kt"),
  get settled() {
    return __t.array(Material);
  },
});
