// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_type::Material;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CollectStarResourcesArgs {
    pub ship_id: u64,
    pub pickup: Vec<Material>,
}

impl From<CollectStarResourcesArgs> for super::Reducer {
    fn from(args: CollectStarResourcesArgs) -> Self {
        Self::CollectStarResources {
            ship_id: args.ship_id,
            pickup: args.pickup,
        }
    }
}

impl __sdk::InModule for CollectStarResourcesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `collect_star_resources`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait collect_star_resources {
    /// Request that the remote module invoke the reducer `collect_star_resources` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`collect_star_resources:collect_star_resources_then`] to run a callback after the reducer completes.
    fn collect_star_resources(&self, ship_id: u64, pickup: Vec<Material>) -> __sdk::Result<()> {
        self.collect_star_resources_then(ship_id, pickup, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `collect_star_resources` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn collect_star_resources_then(
        &self,
        ship_id: u64,
        pickup: Vec<Material>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl collect_star_resources for super::RemoteReducers {
    fn collect_star_resources_then(
        &self,
        ship_id: u64,
        pickup: Vec<Material>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CollectStarResourcesArgs { ship_id, pickup }, callback)
    }
}
