// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::scan_initiator_type::ScanInitiator;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InitiateScanArgs {
    pub scan_initiator: ScanInitiator,
    pub initiator_id: u64,
    pub to_star_x: i32,
    pub to_star_y: i32,
}

impl From<InitiateScanArgs> for super::Reducer {
    fn from(args: InitiateScanArgs) -> Self {
        Self::InitiateScan {
            scan_initiator: args.scan_initiator,
            initiator_id: args.initiator_id,
            to_star_x: args.to_star_x,
            to_star_y: args.to_star_y,
        }
    }
}

impl __sdk::InModule for InitiateScanArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `initiate_scan`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait initiate_scan {
    /// Request that the remote module invoke the reducer `initiate_scan` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`initiate_scan:initiate_scan_then`] to run a callback after the reducer completes.
    fn initiate_scan(
        &self,
        scan_initiator: ScanInitiator,
        initiator_id: u64,
        to_star_x: i32,
        to_star_y: i32,
    ) -> __sdk::Result<()> {
        self.initiate_scan_then(
            scan_initiator,
            initiator_id,
            to_star_x,
            to_star_y,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `initiate_scan` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn initiate_scan_then(
        &self,
        scan_initiator: ScanInitiator,
        initiator_id: u64,
        to_star_x: i32,
        to_star_y: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl initiate_scan for super::RemoteReducers {
    fn initiate_scan_then(
        &self,
        scan_initiator: ScanInitiator,
        initiator_id: u64,
        to_star_x: i32,
        to_star_y: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InitiateScanArgs {
                scan_initiator,
                initiator_id,
                to_star_x,
                to_star_y,
            },
            callback,
        )
    }
}
