// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod building_kind_type;
pub mod building_type;
pub mod collect_star_resources_reducer;
pub mod empire_table;
pub mod empire_type;
pub mod execute_battle_reducer;
pub mod initiate_scan_reducer;
pub mod material_type;
pub mod my_ships_table;
pub mod order_warp_reducer;
pub mod place_building_reducer;
pub mod planet_type_type;
pub mod player_presence_type;
pub mod register_empire_reducer;
pub mod scan_initiator_type;
pub mod scan_job_table;
pub mod scan_job_type;
pub mod scan_result_table;
pub mod scan_result_type;
pub mod scanned_buildling_type;
pub mod scanned_docked_ship_type;
pub mod scanned_planet_type;
pub mod sell_ship_cargo_reducer;
pub mod sell_star_warehouse_reducer;
pub mod set_ship_attack_mode_reducer;
pub mod ship_attack_mode_type;
pub mod ship_stats_type;
pub mod ship_type;
pub mod spawn_starter_ship_reducer;
pub mod star_system_stock_type;
pub mod upgrade_building_reducer;
pub mod visible_buildings_table;
pub mod visible_star_system_stock_table;
pub mod warp_job_type;

pub use building_kind_type::BuildingKind;
pub use building_type::Building;
pub use collect_star_resources_reducer::collect_star_resources;
pub use empire_table::*;
pub use empire_type::Empire;
pub use execute_battle_reducer::execute_battle;
pub use initiate_scan_reducer::initiate_scan;
pub use material_type::Material;
pub use my_ships_table::*;
pub use order_warp_reducer::order_warp;
pub use place_building_reducer::place_building;
pub use planet_type_type::PlanetType;
pub use player_presence_type::PlayerPresence;
pub use register_empire_reducer::register_empire;
pub use scan_initiator_type::ScanInitiator;
pub use scan_job_table::*;
pub use scan_job_type::ScanJob;
pub use scan_result_table::*;
pub use scan_result_type::ScanResult;
pub use scanned_buildling_type::ScannedBuildling;
pub use scanned_docked_ship_type::ScannedDockedShip;
pub use scanned_planet_type::ScannedPlanet;
pub use sell_ship_cargo_reducer::sell_ship_cargo;
pub use sell_star_warehouse_reducer::sell_star_warehouse;
pub use set_ship_attack_mode_reducer::set_ship_attack_mode;
pub use ship_attack_mode_type::ShipAttackMode;
pub use ship_stats_type::ShipStats;
pub use ship_type::Ship;
pub use spawn_starter_ship_reducer::spawn_starter_ship;
pub use star_system_stock_type::StarSystemStock;
pub use upgrade_building_reducer::upgrade_building;
pub use visible_buildings_table::*;
pub use visible_star_system_stock_table::*;
pub use warp_job_type::WarpJob;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    CollectStarResources {
        ship_id: u64,
        pickup: Vec<Material>,
    },
    ExecuteBattle {
        star_x: u32,
        star_y: u32,
    },
    InitiateScan {
        scan_initiator: ScanInitiator,
        initiator_id: u64,
        to_star_x: i32,
        to_star_y: i32,
    },
    OrderWarp {
        ship_id: u64,
        dest_star_x: i32,
        dest_star_y: i32,
    },
    PlaceBuilding {
        star_x: i32,
        star_y: i32,
        planet_index: u8,
        slot_index: u8,
        kind: BuildingKind,
        level: u32,
        mining_resource_index: Option<u8>,
        garrison_attack_mode: Option<ShipAttackMode>,
    },
    RegisterEmpire {
        name: String,
    },
    SellShipCargo {
        ship_id: u64,
        amounts: Vec<Material>,
    },
    SellStarWarehouse {
        ship_id: u64,
        amounts: Vec<Material>,
    },
    SetShipAttackMode {
        ship_id: u64,
        attack_mode: ShipAttackMode,
    },
    SpawnStarterShip,
    UpgradeBuilding {
        building_id: u64,
        new_level: u32,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::CollectStarResources { .. } => "collect_star_resources",
            Reducer::ExecuteBattle { .. } => "execute_battle",
            Reducer::InitiateScan { .. } => "initiate_scan",
            Reducer::OrderWarp { .. } => "order_warp",
            Reducer::PlaceBuilding { .. } => "place_building",
            Reducer::RegisterEmpire { .. } => "register_empire",
            Reducer::SellShipCargo { .. } => "sell_ship_cargo",
            Reducer::SellStarWarehouse { .. } => "sell_star_warehouse",
            Reducer::SetShipAttackMode { .. } => "set_ship_attack_mode",
            Reducer::SpawnStarterShip => "spawn_starter_ship",
            Reducer::UpgradeBuilding { .. } => "upgrade_building",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::CollectStarResources { ship_id, pickup } => {
                __sats::bsatn::to_vec(&collect_star_resources_reducer::CollectStarResourcesArgs {
                    ship_id: ship_id.clone(),
                    pickup: pickup.clone(),
                })
            }
            Reducer::ExecuteBattle { star_x, star_y } => {
                __sats::bsatn::to_vec(&execute_battle_reducer::ExecuteBattleArgs {
                    star_x: star_x.clone(),
                    star_y: star_y.clone(),
                })
            }
            Reducer::InitiateScan {
                scan_initiator,
                initiator_id,
                to_star_x,
                to_star_y,
            } => __sats::bsatn::to_vec(&initiate_scan_reducer::InitiateScanArgs {
                scan_initiator: scan_initiator.clone(),
                initiator_id: initiator_id.clone(),
                to_star_x: to_star_x.clone(),
                to_star_y: to_star_y.clone(),
            }),
            Reducer::OrderWarp {
                ship_id,
                dest_star_x,
                dest_star_y,
            } => __sats::bsatn::to_vec(&order_warp_reducer::OrderWarpArgs {
                ship_id: ship_id.clone(),
                dest_star_x: dest_star_x.clone(),
                dest_star_y: dest_star_y.clone(),
            }),
            Reducer::PlaceBuilding {
                star_x,
                star_y,
                planet_index,
                slot_index,
                kind,
                level,
                mining_resource_index,
                garrison_attack_mode,
            } => __sats::bsatn::to_vec(&place_building_reducer::PlaceBuildingArgs {
                star_x: star_x.clone(),
                star_y: star_y.clone(),
                planet_index: planet_index.clone(),
                slot_index: slot_index.clone(),
                kind: kind.clone(),
                level: level.clone(),
                mining_resource_index: mining_resource_index.clone(),
                garrison_attack_mode: garrison_attack_mode.clone(),
            }),
            Reducer::RegisterEmpire { name } => {
                __sats::bsatn::to_vec(&register_empire_reducer::RegisterEmpireArgs {
                    name: name.clone(),
                })
            }
            Reducer::SellShipCargo { ship_id, amounts } => {
                __sats::bsatn::to_vec(&sell_ship_cargo_reducer::SellShipCargoArgs {
                    ship_id: ship_id.clone(),
                    amounts: amounts.clone(),
                })
            }
            Reducer::SellStarWarehouse { ship_id, amounts } => {
                __sats::bsatn::to_vec(&sell_star_warehouse_reducer::SellStarWarehouseArgs {
                    ship_id: ship_id.clone(),
                    amounts: amounts.clone(),
                })
            }
            Reducer::SetShipAttackMode {
                ship_id,
                attack_mode,
            } => __sats::bsatn::to_vec(&set_ship_attack_mode_reducer::SetShipAttackModeArgs {
                ship_id: ship_id.clone(),
                attack_mode: attack_mode.clone(),
            }),
            Reducer::SpawnStarterShip => {
                __sats::bsatn::to_vec(&spawn_starter_ship_reducer::SpawnStarterShipArgs {})
            }
            Reducer::UpgradeBuilding {
                building_id,
                new_level,
            } => __sats::bsatn::to_vec(&upgrade_building_reducer::UpgradeBuildingArgs {
                building_id: building_id.clone(),
                new_level: new_level.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    empire: __sdk::TableUpdate<Empire>,
    my_ships: __sdk::TableUpdate<Ship>,
    scan_job: __sdk::TableUpdate<ScanJob>,
    scan_result: __sdk::TableUpdate<ScanResult>,
    visible_buildings: __sdk::TableUpdate<Building>,
    visible_star_system_stock: __sdk::TableUpdate<StarSystemStock>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "empire" => db_update
                    .empire
                    .append(empire_table::parse_table_update(table_update)?),
                "my_ships" => db_update
                    .my_ships
                    .append(my_ships_table::parse_table_update(table_update)?),
                "scan_job" => db_update
                    .scan_job
                    .append(scan_job_table::parse_table_update(table_update)?),
                "scan_result" => db_update
                    .scan_result
                    .append(scan_result_table::parse_table_update(table_update)?),
                "visible_buildings" => db_update
                    .visible_buildings
                    .append(visible_buildings_table::parse_table_update(table_update)?),
                "visible_star_system_stock" => db_update.visible_star_system_stock.append(
                    visible_star_system_stock_table::parse_table_update(table_update)?,
                ),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.empire = cache
            .apply_diff_to_table::<Empire>("empire", &self.empire)
            .with_updates_by_pk(|row| &row.identity);
        diff.scan_job = cache
            .apply_diff_to_table::<ScanJob>("scan_job", &self.scan_job)
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.scan_result = cache
            .apply_diff_to_table::<ScanResult>("scan_result", &self.scan_result)
            .with_updates_by_pk(|row| &row.id);
        diff.my_ships = cache.apply_diff_to_table::<Ship>("my_ships", &self.my_ships);
        diff.visible_buildings =
            cache.apply_diff_to_table::<Building>("visible_buildings", &self.visible_buildings);
        diff.visible_star_system_stock = cache.apply_diff_to_table::<StarSystemStock>(
            "visible_star_system_stock",
            &self.visible_star_system_stock,
        );

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "empire" => db_update
                    .empire
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_ships" => db_update
                    .my_ships
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "scan_job" => db_update
                    .scan_job
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "scan_result" => db_update
                    .scan_result
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_buildings" => db_update
                    .visible_buildings
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_star_system_stock" => db_update
                    .visible_star_system_stock
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "empire" => db_update
                    .empire
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_ships" => db_update
                    .my_ships
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "scan_job" => db_update
                    .scan_job
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "scan_result" => db_update
                    .scan_result
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_buildings" => db_update
                    .visible_buildings
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_star_system_stock" => db_update
                    .visible_star_system_stock
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    empire: __sdk::TableAppliedDiff<'r, Empire>,
    my_ships: __sdk::TableAppliedDiff<'r, Ship>,
    scan_job: __sdk::TableAppliedDiff<'r, ScanJob>,
    scan_result: __sdk::TableAppliedDiff<'r, ScanResult>,
    visible_buildings: __sdk::TableAppliedDiff<'r, Building>,
    visible_star_system_stock: __sdk::TableAppliedDiff<'r, StarSystemStock>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Empire>("empire", &self.empire, event);
        callbacks.invoke_table_row_callbacks::<Ship>("my_ships", &self.my_ships, event);
        callbacks.invoke_table_row_callbacks::<ScanJob>("scan_job", &self.scan_job, event);
        callbacks.invoke_table_row_callbacks::<ScanResult>("scan_result", &self.scan_result, event);
        callbacks.invoke_table_row_callbacks::<Building>(
            "visible_buildings",
            &self.visible_buildings,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StarSystemStock>(
            "visible_star_system_stock",
            &self.visible_star_system_stock,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        empire_table::register_table(client_cache);
        my_ships_table::register_table(client_cache);
        scan_job_table::register_table(client_cache);
        scan_result_table::register_table(client_cache);
        visible_buildings_table::register_table(client_cache);
        visible_star_system_stock_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "empire",
        "my_ships",
        "scan_job",
        "scan_result",
        "visible_buildings",
        "visible_star_system_stock",
    ];
}
