// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::material_type::Material;
use super::ship_attack_mode_type::ShipAttackMode;
use super::ship_stats_type::ShipStats;
use super::ship_type::Ship;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ships`.
///
/// Obtain a handle from the [`MyShipsTableAccess::my_ships`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ships()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ships().on_insert(...)`.
pub struct MyShipsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Ship>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ships`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyShipsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyShipsTableHandle`], which mediates access to the table `my_ships`.
    fn my_ships(&self) -> MyShipsTableHandle<'_>;
}

impl MyShipsTableAccess for super::RemoteTables {
    fn my_ships(&self) -> MyShipsTableHandle<'_> {
        MyShipsTableHandle {
            imp: self.imp.get_table::<Ship>("my_ships"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyShipsInsertCallbackId(__sdk::CallbackId);
pub struct MyShipsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyShipsTableHandle<'ctx> {
    type Row = Ship;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Ship> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyShipsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyShipsInsertCallbackId {
        MyShipsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyShipsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyShipsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyShipsDeleteCallbackId {
        MyShipsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyShipsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Ship>("my_ships");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Ship>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Ship>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Ship`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_shipsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Ship`.
    fn my_ships(&self) -> __sdk::__query_builder::Table<Ship>;
}

impl my_shipsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ships(&self) -> __sdk::__query_builder::Table<Ship> {
        __sdk::__query_builder::Table::new("my_ships")
    }
}
