// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OrderWarpArgs {
    pub ship_id: u64,
    pub dest_star_x: i32,
    pub dest_star_y: i32,
}

impl From<OrderWarpArgs> for super::Reducer {
    fn from(args: OrderWarpArgs) -> Self {
        Self::OrderWarp {
            ship_id: args.ship_id,
            dest_star_x: args.dest_star_x,
            dest_star_y: args.dest_star_y,
        }
    }
}

impl __sdk::InModule for OrderWarpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `order_warp`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait order_warp {
    /// Request that the remote module invoke the reducer `order_warp` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`order_warp:order_warp_then`] to run a callback after the reducer completes.
    fn order_warp(&self, ship_id: u64, dest_star_x: i32, dest_star_y: i32) -> __sdk::Result<()> {
        self.order_warp_then(ship_id, dest_star_x, dest_star_y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `order_warp` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn order_warp_then(
        &self,
        ship_id: u64,
        dest_star_x: i32,
        dest_star_y: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl order_warp for super::RemoteReducers {
    fn order_warp_then(
        &self,
        ship_id: u64,
        dest_star_x: i32,
        dest_star_y: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            OrderWarpArgs {
                ship_id,
                dest_star_x,
                dest_star_y,
            },
            callback,
        )
    }
}
