// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_type::Material;
use super::planet_type_type::PlanetType;
use super::scanned_buildling_type::ScannedBuildling;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ScannedPlanet {
    pub index: u8,
    pub name: String,
    pub temperature_k: f64,
    pub planet_type: PlanetType,
    pub size: u8,
    pub richness: f64,
    pub resources: Vec<Material>,
    pub buildlings: Vec<ScannedBuildling>,
}

impl __sdk::InModule for ScannedPlanet {
    type Module = super::RemoteModule;
}
