// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ship_stats_type::ShipStats;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ScannedDockedShip {
    pub owner: __sdk::Identity,
    pub stats: ShipStats,
    pub health: u32,
}

impl __sdk::InModule for ScannedDockedShip {
    type Module = super::RemoteModule;
}
