// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::scan_initiator_type::ScanInitiator;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ScanJob {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub empire_id: __sdk::Identity,
    pub scan_initiator: ScanInitiator,
    pub initiator_id: u64,
    pub ship_id: u64,
    pub to_star_x: i32,
    pub to_star_y: i32,
}

impl __sdk::InModule for ScanJob {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ScanJob`.
///
/// Provides typed access to columns for query building.
pub struct ScanJobCols {
    pub scheduled_id: __sdk::__query_builder::Col<ScanJob, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<ScanJob, __sdk::ScheduleAt>,
    pub empire_id: __sdk::__query_builder::Col<ScanJob, __sdk::Identity>,
    pub scan_initiator: __sdk::__query_builder::Col<ScanJob, ScanInitiator>,
    pub initiator_id: __sdk::__query_builder::Col<ScanJob, u64>,
    pub ship_id: __sdk::__query_builder::Col<ScanJob, u64>,
    pub to_star_x: __sdk::__query_builder::Col<ScanJob, i32>,
    pub to_star_y: __sdk::__query_builder::Col<ScanJob, i32>,
}

impl __sdk::__query_builder::HasCols for ScanJob {
    type Cols = ScanJobCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ScanJobCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            empire_id: __sdk::__query_builder::Col::new(table_name, "empire_id"),
            scan_initiator: __sdk::__query_builder::Col::new(table_name, "scan_initiator"),
            initiator_id: __sdk::__query_builder::Col::new(table_name, "initiator_id"),
            ship_id: __sdk::__query_builder::Col::new(table_name, "ship_id"),
            to_star_x: __sdk::__query_builder::Col::new(table_name, "to_star_x"),
            to_star_y: __sdk::__query_builder::Col::new(table_name, "to_star_y"),
        }
    }
}

/// Indexed column accessor struct for the table `ScanJob`.
///
/// Provides typed access to indexed columns for query building.
pub struct ScanJobIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<ScanJob, u64>,
}

impl __sdk::__query_builder::HasIxCols for ScanJob {
    type IxCols = ScanJobIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ScanJobIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ScanJob {}
