// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::scan_initiator_type::ScanInitiator;
use super::scan_job_type::ScanJob;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `scan_job`.
///
/// Obtain a handle from the [`ScanJobTableAccess::scan_job`] method on [`super::RemoteTables`],
/// like `ctx.db.scan_job()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scan_job().on_insert(...)`.
pub struct ScanJobTableHandle<'ctx> {
    imp: __sdk::TableHandle<ScanJob>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `scan_job`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ScanJobTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ScanJobTableHandle`], which mediates access to the table `scan_job`.
    fn scan_job(&self) -> ScanJobTableHandle<'_>;
}

impl ScanJobTableAccess for super::RemoteTables {
    fn scan_job(&self) -> ScanJobTableHandle<'_> {
        ScanJobTableHandle {
            imp: self.imp.get_table::<ScanJob>("scan_job"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ScanJobInsertCallbackId(__sdk::CallbackId);
pub struct ScanJobDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ScanJobTableHandle<'ctx> {
    type Row = ScanJob;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ScanJob> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ScanJobInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScanJobInsertCallbackId {
        ScanJobInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ScanJobInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ScanJobDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ScanJobDeleteCallbackId {
        ScanJobDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ScanJobDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ScanJobUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ScanJobTableHandle<'ctx> {
    type UpdateCallbackId = ScanJobUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ScanJobUpdateCallbackId {
        ScanJobUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ScanJobUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `scan_job`,
/// which allows point queries on the field of the same name
/// via the [`ScanJobScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scan_job().scheduled_id().find(...)`.
pub struct ScanJobScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ScanJob, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ScanJobTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `scan_job`.
    pub fn scheduled_id(&self) -> ScanJobScheduledIdUnique<'ctx> {
        ScanJobScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ScanJobScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ScanJob> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ScanJob>("scan_job");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ScanJob>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ScanJob>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ScanJob`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait scan_jobQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ScanJob`.
    fn scan_job(&self) -> __sdk::__query_builder::Table<ScanJob>;
}

impl scan_jobQueryTableAccess for __sdk::QueryTableAccessor {
    fn scan_job(&self) -> __sdk::__query_builder::Table<ScanJob> {
        __sdk::__query_builder::Table::new("scan_job")
    }
}
