// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_type::Material;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SellStarWarehouseArgs {
    pub ship_id: u64,
    pub amounts: Vec<Material>,
}

impl From<SellStarWarehouseArgs> for super::Reducer {
    fn from(args: SellStarWarehouseArgs) -> Self {
        Self::SellStarWarehouse {
            ship_id: args.ship_id,
            amounts: args.amounts,
        }
    }
}

impl __sdk::InModule for SellStarWarehouseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sell_star_warehouse`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sell_star_warehouse {
    /// Request that the remote module invoke the reducer `sell_star_warehouse` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sell_star_warehouse:sell_star_warehouse_then`] to run a callback after the reducer completes.
    fn sell_star_warehouse(&self, ship_id: u64, amounts: Vec<Material>) -> __sdk::Result<()> {
        self.sell_star_warehouse_then(ship_id, amounts, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sell_star_warehouse` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sell_star_warehouse_then(
        &self,
        ship_id: u64,
        amounts: Vec<Material>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sell_star_warehouse for super::RemoteReducers {
    fn sell_star_warehouse_then(
        &self,
        ship_id: u64,
        amounts: Vec<Material>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SellStarWarehouseArgs { ship_id, amounts }, callback)
    }
}
