// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_type::Material;
use super::ship_attack_mode_type::ShipAttackMode;
use super::ship_location_type::ShipLocation;
use super::ship_stats_type::ShipStats;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ship {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub stats: ShipStats,
    pub cargo: Vec<Material>,
    pub attack_mode: ShipAttackMode,
    pub location: ShipLocation,
    pub jump_ready_at: __sdk::Timestamp,
}

impl __sdk::InModule for Ship {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Ship`.
///
/// Provides typed access to columns for query building.
pub struct ShipCols {
    pub id: __sdk::__query_builder::Col<Ship, u64>,
    pub owner: __sdk::__query_builder::Col<Ship, __sdk::Identity>,
    pub stats: __sdk::__query_builder::Col<Ship, ShipStats>,
    pub cargo: __sdk::__query_builder::Col<Ship, Vec<Material>>,
    pub attack_mode: __sdk::__query_builder::Col<Ship, ShipAttackMode>,
    pub location: __sdk::__query_builder::Col<Ship, ShipLocation>,
    pub jump_ready_at: __sdk::__query_builder::Col<Ship, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Ship {
    type Cols = ShipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            stats: __sdk::__query_builder::Col::new(table_name, "stats"),
            cargo: __sdk::__query_builder::Col::new(table_name, "cargo"),
            attack_mode: __sdk::__query_builder::Col::new(table_name, "attack_mode"),
            location: __sdk::__query_builder::Col::new(table_name, "location"),
            jump_ready_at: __sdk::__query_builder::Col::new(table_name, "jump_ready_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Ship`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipIxCols {
    pub id: __sdk::__query_builder::IxCol<Ship, u64>,
    pub owner: __sdk::__query_builder::IxCol<Ship, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Ship {
    type IxCols = ShipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ship {}
