// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::material_type::Material;
use super::star_system_stock_type::StarSystemStock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `star_system_stock`.
///
/// Obtain a handle from the [`StarSystemStockTableAccess::star_system_stock`] method on [`super::RemoteTables`],
/// like `ctx.db.star_system_stock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.star_system_stock().on_insert(...)`.
pub struct StarSystemStockTableHandle<'ctx> {
    imp: __sdk::TableHandle<StarSystemStock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `star_system_stock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StarSystemStockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StarSystemStockTableHandle`], which mediates access to the table `star_system_stock`.
    fn star_system_stock(&self) -> StarSystemStockTableHandle<'_>;
}

impl StarSystemStockTableAccess for super::RemoteTables {
    fn star_system_stock(&self) -> StarSystemStockTableHandle<'_> {
        StarSystemStockTableHandle {
            imp: self.imp.get_table::<StarSystemStock>("star_system_stock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StarSystemStockInsertCallbackId(__sdk::CallbackId);
pub struct StarSystemStockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StarSystemStockTableHandle<'ctx> {
    type Row = StarSystemStock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StarSystemStock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StarSystemStockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarSystemStockInsertCallbackId {
        StarSystemStockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StarSystemStockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StarSystemStockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarSystemStockDeleteCallbackId {
        StarSystemStockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StarSystemStockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StarSystemStockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StarSystemStockTableHandle<'ctx> {
    type UpdateCallbackId = StarSystemStockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StarSystemStockUpdateCallbackId {
        StarSystemStockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StarSystemStockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `star_location_id` unique index on the table `star_system_stock`,
/// which allows point queries on the field of the same name
/// via the [`StarSystemStockStarLocationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.star_system_stock().star_location_id().find(...)`.
pub struct StarSystemStockStarLocationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StarSystemStock, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StarSystemStockTableHandle<'ctx> {
    /// Get a handle on the `star_location_id` unique index on the table `star_system_stock`.
    pub fn star_location_id(&self) -> StarSystemStockStarLocationIdUnique<'ctx> {
        StarSystemStockStarLocationIdUnique {
            imp: self.imp.get_unique_constraint::<u128>("star_location_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StarSystemStockStarLocationIdUnique<'ctx> {
    /// Find the subscribed row whose `star_location_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<StarSystemStock> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StarSystemStock>("star_system_stock");
    _table.add_unique_constraint::<u128>("star_location_id", |row| &row.star_location_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StarSystemStock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StarSystemStock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StarSystemStock`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait star_system_stockQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StarSystemStock`.
    fn star_system_stock(&self) -> __sdk::__query_builder::Table<StarSystemStock>;
}

impl star_system_stockQueryTableAccess for __sdk::QueryTableAccessor {
    fn star_system_stock(&self) -> __sdk::__query_builder::Table<StarSystemStock> {
        __sdk::__query_builder::Table::new("star_system_stock")
    }
}
