// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_type::Material;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StarSystemStock {
    pub star_location_id: u128,
    pub star_x: i32,
    pub star_y: i32,
    pub last_settled_at: __sdk::Timestamp,
    pub capacity_kt: f64,
    pub settled: Vec<Material>,
}

impl __sdk::InModule for StarSystemStock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StarSystemStock`.
///
/// Provides typed access to columns for query building.
pub struct StarSystemStockCols {
    pub star_location_id: __sdk::__query_builder::Col<StarSystemStock, u128>,
    pub star_x: __sdk::__query_builder::Col<StarSystemStock, i32>,
    pub star_y: __sdk::__query_builder::Col<StarSystemStock, i32>,
    pub last_settled_at: __sdk::__query_builder::Col<StarSystemStock, __sdk::Timestamp>,
    pub capacity_kt: __sdk::__query_builder::Col<StarSystemStock, f64>,
    pub settled: __sdk::__query_builder::Col<StarSystemStock, Vec<Material>>,
}

impl __sdk::__query_builder::HasCols for StarSystemStock {
    type Cols = StarSystemStockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StarSystemStockCols {
            star_location_id: __sdk::__query_builder::Col::new(table_name, "star_location_id"),
            star_x: __sdk::__query_builder::Col::new(table_name, "star_x"),
            star_y: __sdk::__query_builder::Col::new(table_name, "star_y"),
            last_settled_at: __sdk::__query_builder::Col::new(table_name, "last_settled_at"),
            capacity_kt: __sdk::__query_builder::Col::new(table_name, "capacity_kt"),
            settled: __sdk::__query_builder::Col::new(table_name, "settled"),
        }
    }
}

/// Indexed column accessor struct for the table `StarSystemStock`.
///
/// Provides typed access to indexed columns for query building.
pub struct StarSystemStockIxCols {
    pub star_location_id: __sdk::__query_builder::IxCol<StarSystemStock, u128>,
}

impl __sdk::__query_builder::HasIxCols for StarSystemStock {
    type IxCols = StarSystemStockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StarSystemStockIxCols {
            star_location_id: __sdk::__query_builder::IxCol::new(table_name, "star_location_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StarSystemStock {}
