// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::building_kind_type::BuildingKind;
use super::building_type::Building;
use super::material_type::Material;
use super::ship_attack_mode_type::ShipAttackMode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_buildings`.
///
/// Obtain a handle from the [`VisibleBuildingsTableAccess::visible_buildings`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_buildings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_buildings().on_insert(...)`.
pub struct VisibleBuildingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Building>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_buildings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleBuildingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleBuildingsTableHandle`], which mediates access to the table `visible_buildings`.
    fn visible_buildings(&self) -> VisibleBuildingsTableHandle<'_>;
}

impl VisibleBuildingsTableAccess for super::RemoteTables {
    fn visible_buildings(&self) -> VisibleBuildingsTableHandle<'_> {
        VisibleBuildingsTableHandle {
            imp: self.imp.get_table::<Building>("visible_buildings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleBuildingsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleBuildingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VisibleBuildingsTableHandle<'ctx> {
    type Row = Building;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Building> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleBuildingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleBuildingsInsertCallbackId {
        VisibleBuildingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleBuildingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleBuildingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleBuildingsDeleteCallbackId {
        VisibleBuildingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleBuildingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Building>("visible_buildings");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Building>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Building>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Building`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_buildingsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Building`.
    fn visible_buildings(&self) -> __sdk::__query_builder::Table<Building>;
}

impl visible_buildingsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_buildings(&self) -> __sdk::__query_builder::Table<Building> {
        __sdk::__query_builder::Table::new("visible_buildings")
    }
}
