// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::material_type::Material;
use super::star_system_stock_type::StarSystemStock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_star_system_stock`.
///
/// Obtain a handle from the [`VisibleStarSystemStockTableAccess::visible_star_system_stock`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_star_system_stock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_star_system_stock().on_insert(...)`.
pub struct VisibleStarSystemStockTableHandle<'ctx> {
    imp: __sdk::TableHandle<StarSystemStock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_star_system_stock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleStarSystemStockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleStarSystemStockTableHandle`], which mediates access to the table `visible_star_system_stock`.
    fn visible_star_system_stock(&self) -> VisibleStarSystemStockTableHandle<'_>;
}

impl VisibleStarSystemStockTableAccess for super::RemoteTables {
    fn visible_star_system_stock(&self) -> VisibleStarSystemStockTableHandle<'_> {
        VisibleStarSystemStockTableHandle {
            imp: self
                .imp
                .get_table::<StarSystemStock>("visible_star_system_stock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleStarSystemStockInsertCallbackId(__sdk::CallbackId);
pub struct VisibleStarSystemStockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VisibleStarSystemStockTableHandle<'ctx> {
    type Row = StarSystemStock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StarSystemStock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleStarSystemStockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleStarSystemStockInsertCallbackId {
        VisibleStarSystemStockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleStarSystemStockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleStarSystemStockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleStarSystemStockDeleteCallbackId {
        VisibleStarSystemStockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleStarSystemStockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StarSystemStock>("visible_star_system_stock");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StarSystemStock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StarSystemStock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StarSystemStock`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_star_system_stockQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StarSystemStock`.
    fn visible_star_system_stock(&self) -> __sdk::__query_builder::Table<StarSystemStock>;
}

impl visible_star_system_stockQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_star_system_stock(&self) -> __sdk::__query_builder::Table<StarSystemStock> {
        __sdk::__query_builder::Table::new("visible_star_system_stock")
    }
}
