// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WarpJob {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub ship_id: u64,
    pub to_star_x: i32,
    pub to_star_y: i32,
}

impl __sdk::InModule for WarpJob {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WarpJob`.
///
/// Provides typed access to columns for query building.
pub struct WarpJobCols {
    pub scheduled_id: __sdk::__query_builder::Col<WarpJob, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<WarpJob, __sdk::ScheduleAt>,
    pub ship_id: __sdk::__query_builder::Col<WarpJob, u64>,
    pub to_star_x: __sdk::__query_builder::Col<WarpJob, i32>,
    pub to_star_y: __sdk::__query_builder::Col<WarpJob, i32>,
}

impl __sdk::__query_builder::HasCols for WarpJob {
    type Cols = WarpJobCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WarpJobCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            ship_id: __sdk::__query_builder::Col::new(table_name, "ship_id"),
            to_star_x: __sdk::__query_builder::Col::new(table_name, "to_star_x"),
            to_star_y: __sdk::__query_builder::Col::new(table_name, "to_star_y"),
        }
    }
}

/// Indexed column accessor struct for the table `WarpJob`.
///
/// Provides typed access to indexed columns for query building.
pub struct WarpJobIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<WarpJob, u64>,
}

impl __sdk::__query_builder::HasIxCols for WarpJob {
    type IxCols = WarpJobIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WarpJobIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WarpJob {}
