//! Mirror of server [`vast::building_rules`](../../../spacetimedb/src/building_rules.rs) and
//! [`vast::star_economy`](../../../spacetimedb/src/star_economy.rs) for UI — keep formulas in sync.
//!
//! **Two `Material` types:** [`universe::Material`] is the shared game enum (stock helpers, procgen).
//! [`BindingMaterial`] is generated by `spacetime generate` for the client SDK. When you add a
//! resource variant, update the enum in `universe`, regenerate bindings, and adjust only
//! [`binding_to_universe`] / [`universe_to_binding`] below.

use std::collections::HashMap;

use spacetimedb_sdk::Timestamp;
use universe::generator::StarSystem;
use universe::material_stock::{
    material_from_kind_kt, mining_rates_hash_from_pairs, theoretical_materials_after_accrual,
    total_kt, total_rate_kt_s,
};
use universe::{Material, MaterialKind};
use vast_bindings::{Building, BuildingKind, Material as BindingMaterial};

pub const MAX_BUILDING_LEVEL: usize = 12;

pub const MIN_SHIP_KT_FOR_LEVEL: [u32; MAX_BUILDING_LEVEL] = [
    1, 5, 10, 20, 50, 100, 150, 200, 250, 300, 400, 500,
];

/// Keep in sync with [`vast::building_rules::min_ship_kt_for_level`]. `level` is 1..=MAX (UI slider).
#[inline]
#[must_use]
pub fn min_ship_kt_for_level(level: u32) -> u32 {
    MIN_SHIP_KT_FOR_LEVEL[(level - 1) as usize]
}

#[must_use]
pub fn credits_for_leveled_place(kind: BuildingKind, level: u32) -> Option<u64> {
    let l = level as usize;
    if l < 1 || l > MAX_BUILDING_LEVEL {
        return None;
    }
    let base: u64 = match kind {
        BuildingKind::MiningDepot => 250,
        BuildingKind::Warehouse => 200,
        BuildingKind::MilitaryGarrison => 600,
        BuildingKind::ShipDepot => 300,
        BuildingKind::SalesDepot => return None,
    };
    let lv = l as u64;
    Some(base.saturating_mul(lv.saturating_mul(lv)))
}

#[must_use]
pub fn sales_depot_next_cost(existing_sales_depot_count: u32) -> u64 {
    let n = u32::min(existing_sales_depot_count, 62);
    1000u64.saturating_mul(1u64 << n)
}

#[inline]
#[must_use]
pub fn warehouse_kt_capacity(level: u32) -> f64 {
    f64::from(level)
}

/// Client row → shared [`Material`] (single place to sync with generated bindings).
#[inline]
#[must_use]
pub fn binding_to_universe(m: &BindingMaterial) -> Material {
    match m {
        BindingMaterial::Iron(q) => Material::Iron(*q),
        BindingMaterial::Helium(q) => Material::Helium(*q),
    }
}

/// Shared [`Material`] → client row (inverse of [`binding_to_universe`]).
#[inline]
#[must_use]
pub fn universe_to_binding(m: Material) -> BindingMaterial {
    match m {
        Material::Iron(q) => BindingMaterial::Iron(q),
        Material::Helium(q) => BindingMaterial::Helium(q),
    }
}

#[must_use]
pub fn mining_depot_rate_kt_s(
    level: u32,
    planet_richness: f64,
    material: &BindingMaterial,
    degradation_percent: f32,
) -> f64 {
    let deg = (1.0 - (degradation_percent.clamp(0.0, 100.0) as f64 / 100.0)).max(0.0);
    let mult = binding_to_universe(material).amount();
    f64::from(level) * planet_richness * mult * 0.01 * deg
}

#[must_use]
pub fn garrison_power_units(level: u32, degradation_percent: f32) -> f64 {
    let deg = (1.0 - (degradation_percent.clamp(0.0, 100.0) as f64 / 100.0)).max(0.0);
    f64::from(level) * 100.0 * deg
}

#[inline]
#[must_use]
pub fn ship_depot_concurrent_slots(level: u32) -> u32 {
    level
}

#[must_use]
pub fn capacity_kt_at_star(buildings: &[Building]) -> f64 {
    buildings
        .iter()
        .filter(|b| b.kind == BuildingKind::Warehouse)
        .map(|b| warehouse_kt_capacity(b.level))
        .sum()
}

#[must_use]
pub fn mining_rates_kt_s(sys: &StarSystem, buildings: &[Building]) -> HashMap<MaterialKind, f64> {
    let pairs = buildings
        .iter()
        .filter(|b| b.kind == BuildingKind::MiningDepot)
        .filter_map(|b| {
            let mat = b.mining_material.as_ref()?;
            let planet = sys.planets.iter().find(|p| p.index == b.planet_index)?;
            let r = mining_depot_rate_kt_s(b.level, planet.richness, mat, b.degradation_percent);
            Some((binding_to_universe(mat).kind(), r))
        });
    mining_rates_hash_from_pairs(pairs)
}

#[must_use]
pub fn settled_to_universe(settled: &[BindingMaterial]) -> Vec<Material> {
    settled.iter().map(binding_to_universe).collect()
}

#[must_use]
pub fn total_settled_kt_bindings(settled: &[BindingMaterial]) -> f64 {
    total_kt(&settled_to_universe(settled))
}

/// Build non-zero pickup rows for [`collect_star_resources`] (same order convention as sliders).
#[must_use]
pub fn pickup_vec_for_reducer(amounts: &[f64]) -> Vec<BindingMaterial> {
    debug_assert_eq!(amounts.len(), MaterialKind::ALL.len());
    MaterialKind::ALL
        .iter()
        .zip(amounts)
        .filter_map(|(&k, &kt)| {
            if kt > 0.0 {
                Some(universe_to_binding(material_from_kind_kt(k, kt)))
            } else {
                None
            }
        })
        .collect()
}

/// Match server [`settle_star_resources`](../../../spacetimedb/src/star_economy.rs) `t_eff`.
#[must_use]
pub fn settlement_t_eff(
    now: Timestamp,
    last_settled_at: Timestamp,
    settled: &[Material],
    capacity_kt: f64,
    rates: &HashMap<MaterialKind, f64>,
) -> f64 {
    let total_rate = total_rate_kt_s(rates);
    let dt = elapsed_seconds(now, last_settled_at);
    let remaining_kt = (capacity_kt - total_kt(settled)).max(0.0);
    let t_max = if total_rate > 0.0 {
        remaining_kt / total_rate
    } else {
        f64::INFINITY
    };
    dt.min(t_max)
}

/// Match server [`theoretical_materials_after_accrual`](../../../universe/src/material_stock.rs).
#[must_use]
pub fn theoretical_materials(
    now: Timestamp,
    last_settled_at: Timestamp,
    settled: &[BindingMaterial],
    capacity_kt: f64,
    rates: &HashMap<MaterialKind, f64>,
) -> Vec<Material> {
    let u = settled_to_universe(settled);
    let t_eff = settlement_t_eff(now, last_settled_at, &u, capacity_kt, rates);
    theoretical_materials_after_accrual(&u, rates, t_eff, capacity_kt)
}

#[must_use]
pub fn military_power_at_star(buildings: &[Building]) -> f64 {
    buildings
        .iter()
        .filter(|b| b.kind == BuildingKind::MilitaryGarrison)
        .map(|b| garrison_power_units(b.level, b.degradation_percent))
        .sum()
}

#[must_use]
pub fn ship_build_slots_at_star(buildings: &[Building]) -> u32 {
    buildings
        .iter()
        .filter(|b| b.kind == BuildingKind::ShipDepot)
        .map(|b| ship_depot_concurrent_slots(b.level))
        .sum()
}

#[must_use]
pub fn elapsed_seconds(later: Timestamp, earlier: Timestamp) -> f64 {
    let l = later.to_micros_since_unix_epoch() as i128;
    let e = earlier.to_micros_since_unix_epoch() as i128;
    let d = l - e;
    if d <= 0 {
        return 0.0;
    }
    d as f64 / 1_000_000.0
}
